version: 2
jobs:
  build:
    docker:
      - image: lastcoolnameleft/simdem:latest
    steps:
      - checkout
      - run:
          name: Dump SimDem for README.md
          command: |
            simdem -m dump README.md
      - run:
          name: Run SimDem on main README.md
          command: |
            simdem -d -m test README.md
