version: 2
jobs:
  build:
    docker:
      - image: lastcoolnameleft/simdem:latest
    steps:
      - checkout
      - run:
          name: Print the Current Time
          command: simdem -m test README.md
